2021-12-12 12:01:54 - INFO - logged in
2021-12-12 12:04:08 - INFO - logged in
2021-12-12 12:05:33 - INFO - logged in
2021-12-12 12:13:10 - INFO - logged in
2021-12-12 12:53:49 - INFO - logged in
2021-12-12 13:42:40 - INFO - logged in
2021-12-12 13:45:01 - INFO - logged in
2021-12-12 13:45:43 - INFO - logged in
2021-12-12 13:49:50 - INFO - logged in
2021-12-12 13:52:28 - INFO - logged in
2021-12-12 13:54:03 - INFO - logged in
2021-12-12 13:55:43 - INFO - logged in
2021-12-12 13:56:22 - INFO - logged in
2021-12-12 13:58:11 - INFO - logged in
2021-12-12 13:59:23 - INFO - logged in
2021-12-12 14:03:36 - INFO - logged in
2021-12-12 14:03:39 - INFO - Processing page 1
2021-12-12 14:03:39 - INFO - Found 10 users on this page
2021-12-12 14:03:39 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 14:03:39 - INFO - Sending to Clive George Cook
2021-12-12 14:03:39 - INFO - Using the following replace strings: '<first_name>' = 'Clive'
2021-12-12 14:03:42 - INFO - click_x
2021-12-12 14:03:57 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 14:03:57 - INFO - Sending to Daniel Edwards
2021-12-12 14:03:58 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 352, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 255, in send_message_to_users
    self.send_message_to_user(user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 241, in send_message_to_user
    message_button.click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span class="artdeco-button__text">...</span> is not clickable at point (785, 390). Other element would receive the click: <a class="app-aware-link artdeco-button
            artdeco-button--secondary
            artdeco-button--1 feed-shared-event__cta
            " aria-label="View event: Deep-Tech Showcase: Aerospace &amp; Defense" data-control-id="" data-control-name="event_share_card_cta" href="https://www.linkedin.com/events/deep-techshowcase-aerospace-def6805797022231207936/">...</a>
  (Session info: chrome=96.0.4664.45)
Stacktrace:
Backtrace:
	Ordinal0 [0x004C6903+2517251]
	Ordinal0 [0x0045F8E1+2095329]
	Ordinal0 [0x00362848+1058888]
	Ordinal0 [0x00393509+1258761]
	Ordinal0 [0x00391868+1251432]
	Ordinal0 [0x0038F65D+1242717]
	Ordinal0 [0x0038E4A8+1238184]
	Ordinal0 [0x00384037+1196087]
	Ordinal0 [0x003A64D3+1336531]
	Ordinal0 [0x00383A36+1194550]
	Ordinal0 [0x003A65BA+1336762]
	Ordinal0 [0x003B5BBF+1399743]
	Ordinal0 [0x003A639B+1336219]
	Ordinal0 [0x003827A7+1189799]
	Ordinal0 [0x00383609+1193481]
	GetHandleVerifier [0x00655904+1577972]
	GetHandleVerifier [0x00700B97+2279047]
	GetHandleVerifier [0x00556D09+534521]
	GetHandleVerifier [0x00555DB9+530601]
	Ordinal0 [0x00464FF9+2117625]
	Ordinal0 [0x004698A8+2136232]
	Ordinal0 [0x004699E2+2136546]
	Ordinal0 [0x00473541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 14:03:58 - INFO - Done
2021-12-12 14:09:26 - INFO - logged in
2021-12-12 14:12:45 - INFO - Processing page 1
2021-12-12 14:14:30 - INFO - Found 10 users on this page
2021-12-12 14:15:34 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 14:16:00 - INFO - Already delivered to Clive George Cook
2021-12-12 14:16:55 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 14:17:47 - INFO - Sending to Daniel Edwards
2021-12-12 14:18:29 - INFO - Using the following replace strings: '<first_name>' = 'Daniel'
2021-12-12 14:18:48 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 352, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 255, in send_message_to_users
    self.send_message_to_user(user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 243, in send_message_to_user
    self.send_message(message)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 261, in send_message
    msgwin = self.driver.find_element_by_css_selector(".msg-form__contenteditable")
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 808, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".msg-form__contenteditable"}
  (Session info: chrome=96.0.4664.45)
Stacktrace:
Backtrace:
	Ordinal0 [0x004C6903+2517251]
	Ordinal0 [0x0045F8E1+2095329]
	Ordinal0 [0x00362848+1058888]
	Ordinal0 [0x0038D448+1233992]
	Ordinal0 [0x0038D63B+1234491]
	Ordinal0 [0x003B7812+1406994]
	Ordinal0 [0x003A650A+1336586]
	Ordinal0 [0x003B5BBF+1399743]
	Ordinal0 [0x003A639B+1336219]
	Ordinal0 [0x003827A7+1189799]
	Ordinal0 [0x00383609+1193481]
	GetHandleVerifier [0x00655904+1577972]
	GetHandleVerifier [0x00700B97+2279047]
	GetHandleVerifier [0x00556D09+534521]
	GetHandleVerifier [0x00555DB9+530601]
	Ordinal0 [0x00464FF9+2117625]
	Ordinal0 [0x004698A8+2136232]
	Ordinal0 [0x004699E2+2136546]
	Ordinal0 [0x00473541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 14:18:51 - INFO - Done
2021-12-12 15:17:47 - INFO - logged in
2021-12-12 15:17:57 - INFO - Processing page 1
2021-12-12 15:17:59 - INFO - Found 10 users on this page
2021-12-12 15:18:07 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 15:18:09 - INFO - Already delivered to Clive George Cook
2021-12-12 15:18:10 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 15:18:11 - INFO - Sending to Daniel Edwards
2021-12-12 15:31:43 - INFO - logged in
2021-12-12 15:32:00 - INFO - Processing page 1
2021-12-12 15:32:01 - INFO - Found 10 users on this page
2021-12-12 15:32:02 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 15:32:02 - INFO - Already delivered to Clive George Cook
2021-12-12 15:32:02 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 15:32:02 - INFO - Sending to Daniel Edwards
2021-12-12 15:41:57 - INFO - logged in
2021-12-12 15:42:00 - INFO - Processing page 1
2021-12-12 15:42:00 - INFO - Found 10 users on this page
2021-12-12 15:42:00 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 15:42:00 - INFO - Already delivered to Clive George Cook
2021-12-12 15:42:00 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 15:42:00 - INFO - Sending to Daniel Edwards
2021-12-12 15:44:26 - INFO - logged in
2021-12-12 15:44:29 - INFO - Processing page 1
2021-12-12 15:44:29 - INFO - Found 10 users on this page
2021-12-12 15:44:29 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 15:44:29 - INFO - Already delivered to Clive George Cook
2021-12-12 15:44:29 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 15:44:29 - INFO - Sending to Daniel Edwards
2021-12-12 15:44:29 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 338, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 223, in send_message_to_user
    message_button = self.get_message_button(userNum, user_element)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 276, in get_message_button
    return user_element.find_element_by_xpath("//div/div/div[3]/ul/li[{0}]/div/div/div[3]/button", userNum)
TypeError: find_element_by_xpath() takes 2 positional arguments but 3 were given
2021-12-12 15:44:33 - INFO - Done
2021-12-12 15:50:48 - INFO - logged in
2021-12-12 15:50:51 - INFO - Processing page 1
2021-12-12 15:50:51 - INFO - Found 10 users on this page
2021-12-12 15:50:51 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 15:50:51 - INFO - Already delivered to Clive George Cook
2021-12-12 15:50:51 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 15:50:51 - INFO - Sending to Daniel Edwards
2021-12-12 15:50:51 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 341, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 223, in send_message_to_user
    message_button = self.get_message_button(userNum, user_element)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 277, in get_message_button
    xpathB.replace("{0}", userNum)
TypeError: replace() argument 2 must be str, not int
2021-12-12 15:50:55 - INFO - Done
2021-12-12 15:52:36 - INFO - logged in
2021-12-12 15:52:39 - INFO - Processing page 1
2021-12-12 15:52:39 - INFO - Found 10 users on this page
2021-12-12 15:52:39 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 15:52:39 - INFO - Already delivered to Clive George Cook
2021-12-12 15:52:39 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 15:52:39 - INFO - Sending to Daniel Edwards
2021-12-12 15:52:39 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 341, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 223, in send_message_to_user
    message_button = self.get_message_button(userNum, user_element)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 279, in get_message_button
    return user_element.find_element_by_xpath("//div/div/div[3]/ul/li[{0}]/div/div/div[3]/button", userNum)
TypeError: find_element_by_xpath() takes 2 positional arguments but 3 were given
2021-12-12 15:52:43 - INFO - Done
2021-12-12 15:53:53 - INFO - logged in
2021-12-12 15:53:56 - INFO - Processing page 1
2021-12-12 15:53:56 - INFO - Found 10 users on this page
2021-12-12 15:53:56 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 15:53:56 - INFO - Already delivered to Clive George Cook
2021-12-12 15:53:56 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 15:53:56 - INFO - Sending to Daniel Edwards
2021-12-12 15:54:01 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 341, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 223, in send_message_to_user
    message_button = self.get_message_button(userNum, user_element)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 279, in get_message_button
    return user_element.find_element_by_xpath(xpathB)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 735, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div/div/div[3]/ul/li[tempi]/div/div/div[3]/button"}
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00AA6903+2517251]
	Ordinal0 [0x00A3F8E1+2095329]
	Ordinal0 [0x00942848+1058888]
	Ordinal0 [0x0096D448+1233992]
	Ordinal0 [0x0096D63B+1234491]
	Ordinal0 [0x00963AB1+1194673]
	Ordinal0 [0x0098650A+1336586]
	Ordinal0 [0x00963A36+1194550]
	Ordinal0 [0x009865BA+1336762]
	Ordinal0 [0x00995BBF+1399743]
	Ordinal0 [0x0098639B+1336219]
	Ordinal0 [0x009627A7+1189799]
	Ordinal0 [0x00963609+1193481]
	GetHandleVerifier [0x00C35904+1577972]
	GetHandleVerifier [0x00CE0B97+2279047]
	GetHandleVerifier [0x00B36D09+534521]
	GetHandleVerifier [0x00B35DB9+530601]
	Ordinal0 [0x00A44FF9+2117625]
	Ordinal0 [0x00A498A8+2136232]
	Ordinal0 [0x00A499E2+2136546]
	Ordinal0 [0x00A53541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 15:54:05 - INFO - Done
2021-12-12 15:56:40 - INFO - logged in
2021-12-12 15:56:42 - INFO - Processing page 1
2021-12-12 15:56:42 - INFO - Found 10 users on this page
2021-12-12 15:56:42 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 15:56:42 - INFO - Already delivered to Clive George Cook
2021-12-12 15:56:42 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 15:56:42 - INFO - Sending to Daniel Edwards
2021-12-12 15:56:47 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 343, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 223, in send_message_to_user
    message_button = self.get_message_button(userNum, user_element)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 281, in get_message_button
    return user_element.find_element_by_xpath(xpathB)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 735, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div/div/div[3]/ul/li[tempi]/div/div/div[3]/button"}
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00AA6903+2517251]
	Ordinal0 [0x00A3F8E1+2095329]
	Ordinal0 [0x00942848+1058888]
	Ordinal0 [0x0096D448+1233992]
	Ordinal0 [0x0096D63B+1234491]
	Ordinal0 [0x00963AB1+1194673]
	Ordinal0 [0x0098650A+1336586]
	Ordinal0 [0x00963A36+1194550]
	Ordinal0 [0x009865BA+1336762]
	Ordinal0 [0x00995BBF+1399743]
	Ordinal0 [0x0098639B+1336219]
	Ordinal0 [0x009627A7+1189799]
	Ordinal0 [0x00963609+1193481]
	GetHandleVerifier [0x00C35904+1577972]
	GetHandleVerifier [0x00CE0B97+2279047]
	GetHandleVerifier [0x00B36D09+534521]
	GetHandleVerifier [0x00B35DB9+530601]
	Ordinal0 [0x00A44FF9+2117625]
	Ordinal0 [0x00A498A8+2136232]
	Ordinal0 [0x00A499E2+2136546]
	Ordinal0 [0x00A53541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 15:56:48 - INFO - Done
2021-12-12 15:58:09 - INFO - logged in
2021-12-12 15:58:12 - INFO - Processing page 1
2021-12-12 15:58:12 - INFO - Found 10 users on this page
2021-12-12 15:58:12 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 15:58:12 - INFO - Already delivered to Clive George Cook
2021-12-12 15:58:12 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 15:58:12 - INFO - Sending to Daniel Edwards
2021-12-12 15:58:13 - INFO - Using the following replace strings: '<first_name>' = 'Daniel'
2021-12-12 15:58:15 - INFO - click_x
2021-12-12 15:58:30 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 15:58:30 - INFO - Sending to Philip D'Amelia
2021-12-12 15:58:31 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 343, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 224, in send_message_to_user
    message_button.click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id="ember122" class="artdeco-button artdeco-button--2 artdeco-button--secondary ember-view">...</button> is not clickable at point (785, 500). Other element would receive the click: <div class="msg-form__contenteditable t-14 t-black--light t-normal flex-grow-1 full-height notranslate
      " contenteditable="true" role="textbox" aria-multiline="true" aria-label="Write a message…">...</div>
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00AA6903+2517251]
	Ordinal0 [0x00A3F8E1+2095329]
	Ordinal0 [0x00942848+1058888]
	Ordinal0 [0x00973509+1258761]
	Ordinal0 [0x00971868+1251432]
	Ordinal0 [0x0096F65D+1242717]
	Ordinal0 [0x0096E4A8+1238184]
	Ordinal0 [0x00964037+1196087]
	Ordinal0 [0x009864D3+1336531]
	Ordinal0 [0x00963A36+1194550]
	Ordinal0 [0x009865BA+1336762]
	Ordinal0 [0x00995BBF+1399743]
	Ordinal0 [0x0098639B+1336219]
	Ordinal0 [0x009627A7+1189799]
	Ordinal0 [0x00963609+1193481]
	GetHandleVerifier [0x00C35904+1577972]
	GetHandleVerifier [0x00CE0B97+2279047]
	GetHandleVerifier [0x00B36D09+534521]
	GetHandleVerifier [0x00B35DB9+530601]
	Ordinal0 [0x00A44FF9+2117625]
	Ordinal0 [0x00A498A8+2136232]
	Ordinal0 [0x00A499E2+2136546]
	Ordinal0 [0x00A53541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 15:58:32 - INFO - Done
2021-12-12 16:20:05 - INFO - logged in
2021-12-12 16:20:07 - INFO - Processing page 1
2021-12-12 16:20:07 - INFO - Found 10 users on this page
2021-12-12 16:20:07 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 16:20:07 - INFO - Already delivered to Clive George Cook
2021-12-12 16:20:07 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 16:20:07 - INFO - Already delivered to Daniel Edwards
2021-12-12 16:20:07 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 16:20:07 - INFO - Sending to Philip D'Amelia
2021-12-12 16:20:08 - INFO - Using the following replace strings: '<first_name>' = 'Philip'
2021-12-12 16:20:10 - INFO - click_x
2021-12-12 16:20:25 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-12 16:20:25 - INFO - Sending to Neeraj Kashyap
2021-12-12 16:20:27 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 342, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 224, in send_message_to_user
    message_button.click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id="ember129" class="artdeco-button artdeco-button--2 artdeco-button--secondary ember-view">...</button> is not clickable at point (785, 548). Other element would receive the click: <footer aria-label="Compose actions for your conversation with Philip D&amp;amp;#39;Amelia" class="msg-form__footer flex-shrink-zero ">...</footer>
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00AA6903+2517251]
	Ordinal0 [0x00A3F8E1+2095329]
	Ordinal0 [0x00942848+1058888]
	Ordinal0 [0x00973509+1258761]
	Ordinal0 [0x00971868+1251432]
	Ordinal0 [0x0096F65D+1242717]
	Ordinal0 [0x0096E4A8+1238184]
	Ordinal0 [0x00964037+1196087]
	Ordinal0 [0x009864D3+1336531]
	Ordinal0 [0x00963A36+1194550]
	Ordinal0 [0x009865BA+1336762]
	Ordinal0 [0x00995BBF+1399743]
	Ordinal0 [0x0098639B+1336219]
	Ordinal0 [0x009627A7+1189799]
	Ordinal0 [0x00963609+1193481]
	GetHandleVerifier [0x00C35904+1577972]
	GetHandleVerifier [0x00CE0B97+2279047]
	GetHandleVerifier [0x00B36D09+534521]
	GetHandleVerifier [0x00B35DB9+530601]
	Ordinal0 [0x00A44FF9+2117625]
	Ordinal0 [0x00A498A8+2136232]
	Ordinal0 [0x00A499E2+2136546]
	Ordinal0 [0x00A53541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 16:20:31 - INFO - Done
2021-12-12 16:21:29 - INFO - logged in
2021-12-12 16:21:32 - INFO - Processing page 1
2021-12-12 16:21:32 - INFO - Found 10 users on this page
2021-12-12 16:21:32 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 16:21:32 - INFO - Already delivered to Clive George Cook
2021-12-12 16:21:32 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 16:21:32 - INFO - Already delivered to Daniel Edwards
2021-12-12 16:21:32 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 16:21:32 - INFO - Already delivered to Philip D'Amelia
2021-12-12 16:21:32 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-12 16:21:32 - INFO - Sending to Neeraj Kashyap
2021-12-12 16:21:32 - INFO - Using the following replace strings: '<first_name>' = 'Neeraj'
2021-12-12 16:22:37 - INFO - click_x
2021-12-12 16:24:54 - INFO - logged in
2021-12-12 16:24:57 - INFO - Processing page 1
2021-12-12 16:24:57 - INFO - Found 10 users on this page
2021-12-12 16:24:57 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 16:24:57 - INFO - Already delivered to Clive George Cook
2021-12-12 16:24:57 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 16:24:57 - INFO - Already delivered to Daniel Edwards
2021-12-12 16:24:57 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 16:24:57 - INFO - Already delivered to Philip D'Amelia
2021-12-12 16:24:57 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-12 16:24:57 - INFO - Sending to Neeraj Kashyap
2021-12-12 16:24:57 - INFO - Using the following replace strings: '<first_name>' = 'Neeraj'
2021-12-12 16:25:00 - INFO - click_x
2021-12-12 16:25:20 - INFO - Found user's name: 'Eric Gallagher'
2021-12-12 16:25:20 - INFO - Sending to Eric Gallagher
2021-12-12 16:25:21 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 346, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 224, in send_message_to_user
    message_button.click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id="ember130" class="artdeco-button artdeco-button--2 artdeco-button--secondary ember-view">...</button> is not clickable at point (785, 358). Other element would receive the click: <span>...</span>
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00AA6903+2517251]
	Ordinal0 [0x00A3F8E1+2095329]
	Ordinal0 [0x00942848+1058888]
	Ordinal0 [0x00973509+1258761]
	Ordinal0 [0x00971868+1251432]
	Ordinal0 [0x0096F65D+1242717]
	Ordinal0 [0x0096E4A8+1238184]
	Ordinal0 [0x00964037+1196087]
	Ordinal0 [0x009864D3+1336531]
	Ordinal0 [0x00963A36+1194550]
	Ordinal0 [0x009865BA+1336762]
	Ordinal0 [0x00995BBF+1399743]
	Ordinal0 [0x0098639B+1336219]
	Ordinal0 [0x009627A7+1189799]
	Ordinal0 [0x00963609+1193481]
	GetHandleVerifier [0x00C35904+1577972]
	GetHandleVerifier [0x00CE0B97+2279047]
	GetHandleVerifier [0x00B36D09+534521]
	GetHandleVerifier [0x00B35DB9+530601]
	Ordinal0 [0x00A44FF9+2117625]
	Ordinal0 [0x00A498A8+2136232]
	Ordinal0 [0x00A499E2+2136546]
	Ordinal0 [0x00A53541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 16:25:25 - INFO - Done
2021-12-12 16:29:30 - INFO - logged in
2021-12-12 16:29:33 - INFO - Processing page 1
2021-12-12 16:29:43 - INFO - Found 10 users on this page
2021-12-12 16:30:02 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 16:30:06 - INFO - Already delivered to Clive George Cook
2021-12-12 16:30:08 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 16:30:11 - INFO - Already delivered to Daniel Edwards
2021-12-12 16:30:15 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 16:30:17 - INFO - Already delivered to Philip D'Amelia
2021-12-12 16:30:18 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-12 16:30:20 - INFO - Already delivered to Neeraj Kashyap
2021-12-12 16:30:22 - INFO - Found user's name: 'Eric Gallagher'
2021-12-12 16:30:23 - INFO - Sending to Eric Gallagher
2021-12-12 16:31:14 - INFO - Using the following replace strings: '<first_name>' = 'Eric'
2021-12-12 16:31:18 - INFO - click_x
2021-12-12 16:31:55 - INFO - Found user's name: 'Dan Keller'
2021-12-12 16:31:57 - INFO - Sending to Dan Keller
2021-12-12 16:32:03 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 346, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 224, in send_message_to_user
    message_button.click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id="ember125" class="artdeco-button artdeco-button--2 artdeco-button--secondary ember-view">...</button> is not clickable at point (601, 512). Other element would receive the click: <div class="msg-form__hint-text t-12 t-black--light t-normal">...</div>
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00AA6903+2517251]
	Ordinal0 [0x00A3F8E1+2095329]
	Ordinal0 [0x00942848+1058888]
	Ordinal0 [0x00973509+1258761]
	Ordinal0 [0x00971868+1251432]
	Ordinal0 [0x0096F65D+1242717]
	Ordinal0 [0x0096E4A8+1238184]
	Ordinal0 [0x00964037+1196087]
	Ordinal0 [0x009864D3+1336531]
	Ordinal0 [0x00963A36+1194550]
	Ordinal0 [0x009865BA+1336762]
	Ordinal0 [0x00995BBF+1399743]
	Ordinal0 [0x0098639B+1336219]
	Ordinal0 [0x009627A7+1189799]
	Ordinal0 [0x00963609+1193481]
	GetHandleVerifier [0x00C35904+1577972]
	GetHandleVerifier [0x00CE0B97+2279047]
	GetHandleVerifier [0x00B36D09+534521]
	GetHandleVerifier [0x00B35DB9+530601]
	Ordinal0 [0x00A44FF9+2117625]
	Ordinal0 [0x00A498A8+2136232]
	Ordinal0 [0x00A499E2+2136546]
	Ordinal0 [0x00A53541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 16:53:50 - INFO - logged in
2021-12-12 16:53:52 - INFO - Processing page 1
2021-12-12 16:53:53 - INFO - Found 10 users on this page
2021-12-12 16:53:53 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 16:53:53 - INFO - Already delivered to Clive George Cook
2021-12-12 16:53:53 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 16:53:53 - INFO - Already delivered to Daniel Edwards
2021-12-12 16:53:53 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 16:53:53 - INFO - Already delivered to Philip D'Amelia
2021-12-12 16:53:53 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-12 16:53:53 - INFO - Already delivered to Neeraj Kashyap
2021-12-12 16:53:53 - INFO - Found user's name: 'Eric Gallagher'
2021-12-12 16:53:53 - INFO - Already delivered to Eric Gallagher
2021-12-12 16:53:53 - INFO - Found user's name: 'Dan Keller'
2021-12-12 16:53:53 - INFO - Sending to Dan Keller
2021-12-12 16:53:53 - INFO - Using the following replace strings: '<first_name>' = 'Dan'
2021-12-12 16:53:56 - INFO - click_x
2021-12-12 16:54:11 - INFO - Found user's name: 'Aron Einhorn'
2021-12-12 16:54:11 - INFO - Sending to Aron Einhorn
2021-12-12 16:54:12 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 346, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 224, in send_message_to_user
    message_button.click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id="ember131" class="artdeco-button artdeco-button--2 artdeco-button--secondary ember-view">...</button> is not clickable at point (785, 238). Other element would receive the click: <div class="flex-grow-1 t-normal " tabindex="0">...</div>
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00AA6903+2517251]
	Ordinal0 [0x00A3F8E1+2095329]
	Ordinal0 [0x00942848+1058888]
	Ordinal0 [0x00973509+1258761]
	Ordinal0 [0x00971868+1251432]
	Ordinal0 [0x0096F65D+1242717]
	Ordinal0 [0x0096E4A8+1238184]
	Ordinal0 [0x00964037+1196087]
	Ordinal0 [0x009864D3+1336531]
	Ordinal0 [0x00963A36+1194550]
	Ordinal0 [0x009865BA+1336762]
	Ordinal0 [0x00995BBF+1399743]
	Ordinal0 [0x0098639B+1336219]
	Ordinal0 [0x009627A7+1189799]
	Ordinal0 [0x00963609+1193481]
	GetHandleVerifier [0x00C35904+1577972]
	GetHandleVerifier [0x00CE0B97+2279047]
	GetHandleVerifier [0x00B36D09+534521]
	GetHandleVerifier [0x00B35DB9+530601]
	Ordinal0 [0x00A44FF9+2117625]
	Ordinal0 [0x00A498A8+2136232]
	Ordinal0 [0x00A499E2+2136546]
	Ordinal0 [0x00A53541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 16:54:16 - INFO - Done
2021-12-12 16:56:38 - INFO - logged in
2021-12-12 16:56:41 - INFO - Processing page 1
2021-12-12 16:56:41 - INFO - Found 10 users on this page
2021-12-12 16:56:41 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 16:56:41 - INFO - Already delivered to Clive George Cook
2021-12-12 16:56:41 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 16:56:41 - INFO - Already delivered to Daniel Edwards
2021-12-12 16:56:41 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 16:56:41 - INFO - Already delivered to Philip D'Amelia
2021-12-12 16:56:41 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-12 16:56:41 - INFO - Already delivered to Neeraj Kashyap
2021-12-12 16:56:41 - INFO - Found user's name: 'Eric Gallagher'
2021-12-12 16:56:41 - INFO - Already delivered to Eric Gallagher
2021-12-12 16:56:41 - INFO - Found user's name: 'Dan Keller'
2021-12-12 16:56:41 - INFO - Already delivered to Dan Keller
2021-12-12 16:56:41 - INFO - Found user's name: 'Aron Einhorn'
2021-12-12 16:56:41 - INFO - Sending to Aron Einhorn
2021-12-12 16:56:41 - INFO - Using the following replace strings: '<first_name>' = 'Aron'
2021-12-12 16:56:44 - INFO - click_x
2021-12-12 16:57:04 - INFO - Found user's name: 'soner haci'
2021-12-12 16:57:04 - INFO - Sending to soner haci
2021-12-12 16:57:05 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 350, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 224, in send_message_to_user
    message_button.click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id="ember132" class="artdeco-button artdeco-button--2 artdeco-button--secondary ember-view">...</button> is not clickable at point (785, 548). Other element would receive the click: <footer aria-label="Compose actions for your conversation with Aron Einhorn" class="msg-form__footer flex-shrink-zero ">...</footer>
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00AA6903+2517251]
	Ordinal0 [0x00A3F8E1+2095329]
	Ordinal0 [0x00942848+1058888]
	Ordinal0 [0x00973509+1258761]
	Ordinal0 [0x00971868+1251432]
	Ordinal0 [0x0096F65D+1242717]
	Ordinal0 [0x0096E4A8+1238184]
	Ordinal0 [0x00964037+1196087]
	Ordinal0 [0x009864D3+1336531]
	Ordinal0 [0x00963A36+1194550]
	Ordinal0 [0x009865BA+1336762]
	Ordinal0 [0x00995BBF+1399743]
	Ordinal0 [0x0098639B+1336219]
	Ordinal0 [0x009627A7+1189799]
	Ordinal0 [0x00963609+1193481]
	GetHandleVerifier [0x00C35904+1577972]
	GetHandleVerifier [0x00CE0B97+2279047]
	GetHandleVerifier [0x00B36D09+534521]
	GetHandleVerifier [0x00B35DB9+530601]
	Ordinal0 [0x00A44FF9+2117625]
	Ordinal0 [0x00A498A8+2136232]
	Ordinal0 [0x00A499E2+2136546]
	Ordinal0 [0x00A53541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 16:57:09 - INFO - Done
2021-12-12 17:01:13 - INFO - logged in
2021-12-12 17:01:16 - INFO - Processing page 1
2021-12-12 17:01:16 - INFO - Found 10 users on this page
2021-12-12 17:01:16 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 17:01:16 - INFO - Already delivered to Clive George Cook
2021-12-12 17:01:16 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 17:01:16 - INFO - Already delivered to Daniel Edwards
2021-12-12 17:01:16 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 17:01:16 - INFO - Already delivered to Philip D'Amelia
2021-12-12 17:01:16 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-12 17:01:16 - INFO - Already delivered to Neeraj Kashyap
2021-12-12 17:01:16 - INFO - Found user's name: 'Eric Gallagher'
2021-12-12 17:01:16 - INFO - Already delivered to Eric Gallagher
2021-12-12 17:01:16 - INFO - Found user's name: 'Dan Keller'
2021-12-12 17:01:16 - INFO - Already delivered to Dan Keller
2021-12-12 17:01:16 - INFO - Found user's name: 'Aron Einhorn'
2021-12-12 17:01:16 - INFO - Already delivered to Aron Einhorn
2021-12-12 17:01:16 - INFO - Found user's name: 'soner haci'
2021-12-12 17:01:16 - INFO - Sending to soner haci
2021-12-12 17:01:16 - INFO - Using the following replace strings: '<first_name>' = 'soner'
2021-12-12 17:01:19 - INFO - click_x
2021-12-12 17:01:34 - INFO - Found user's name: 'Yohei Iwasaki'
2021-12-12 17:01:34 - INFO - Sending to Yohei Iwasaki
2021-12-12 17:01:35 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 350, in <module>
    page.send_message_to_users(user_elements)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 239, in send_message_to_users
    self.send_message_to_user(userNum, user_element, first_name=first_name)
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 224, in send_message_to_user
    message_button.click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id="ember133" class="artdeco-button artdeco-button--2 artdeco-button--secondary ember-view">...</button> is not clickable at point (785, 548). Other element would receive the click: <footer aria-label="Compose actions for your conversation with soner haci" class="msg-form__footer flex-shrink-zero ">...</footer>
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00AA6903+2517251]
	Ordinal0 [0x00A3F8E1+2095329]
	Ordinal0 [0x00942848+1058888]
	Ordinal0 [0x00973509+1258761]
	Ordinal0 [0x00971868+1251432]
	Ordinal0 [0x0096F65D+1242717]
	Ordinal0 [0x0096E4A8+1238184]
	Ordinal0 [0x00964037+1196087]
	Ordinal0 [0x009864D3+1336531]
	Ordinal0 [0x00963A36+1194550]
	Ordinal0 [0x009865BA+1336762]
	Ordinal0 [0x00995BBF+1399743]
	Ordinal0 [0x0098639B+1336219]
	Ordinal0 [0x009627A7+1189799]
	Ordinal0 [0x00963609+1193481]
	GetHandleVerifier [0x00C35904+1577972]
	GetHandleVerifier [0x00CE0B97+2279047]
	GetHandleVerifier [0x00B36D09+534521]
	GetHandleVerifier [0x00B35DB9+530601]
	Ordinal0 [0x00A44FF9+2117625]
	Ordinal0 [0x00A498A8+2136232]
	Ordinal0 [0x00A499E2+2136546]
	Ordinal0 [0x00A53541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-12 17:01:35 - INFO - Done
2021-12-12 17:02:36 - INFO - logged in
2021-12-12 17:02:38 - INFO - Processing page 1
2021-12-12 17:03:34 - INFO - Found 10 users on this page
2021-12-12 17:03:36 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 17:03:36 - INFO - Already delivered to Clive George Cook
2021-12-12 17:03:36 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 17:03:36 - INFO - Already delivered to Daniel Edwards
2021-12-12 17:03:36 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 17:03:36 - INFO - Already delivered to Philip D'Amelia
2021-12-12 17:03:36 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-12 17:03:36 - INFO - Already delivered to Neeraj Kashyap
2021-12-12 17:03:36 - INFO - Found user's name: 'Eric Gallagher'
2021-12-12 17:03:36 - INFO - Already delivered to Eric Gallagher
2021-12-12 17:03:36 - INFO - Found user's name: 'Dan Keller'
2021-12-12 17:03:36 - INFO - Already delivered to Dan Keller
2021-12-12 17:03:36 - INFO - Found user's name: 'Aron Einhorn'
2021-12-12 17:03:36 - INFO - Already delivered to Aron Einhorn
2021-12-12 17:03:36 - INFO - Found user's name: 'soner haci'
2021-12-12 17:03:36 - INFO - Already delivered to soner haci
2021-12-12 17:03:36 - INFO - Found user's name: 'Yohei Iwasaki'
2021-12-12 17:03:36 - INFO - Sending to Yohei Iwasaki
2021-12-12 17:03:36 - INFO - Using the following replace strings: '<first_name>' = 'Yohei'
2021-12-12 17:03:57 - INFO - click_x
2021-12-12 17:06:46 - INFO - logged in
2021-12-12 17:06:48 - INFO - Processing page 1
2021-12-12 17:06:48 - INFO - Found 10 users on this page
2021-12-12 17:06:48 - INFO - Found user's name: 'Clive George Cook'
2021-12-12 17:06:48 - INFO - Already delivered to Clive George Cook
2021-12-12 17:06:48 - INFO - Found user's name: 'Daniel Edwards'
2021-12-12 17:06:48 - INFO - Already delivered to Daniel Edwards
2021-12-12 17:06:48 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-12 17:06:48 - INFO - Already delivered to Philip D'Amelia
2021-12-12 17:06:48 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-12 17:06:48 - INFO - Already delivered to Neeraj Kashyap
2021-12-12 17:06:48 - INFO - Found user's name: 'Eric Gallagher'
2021-12-12 17:06:48 - INFO - Already delivered to Eric Gallagher
2021-12-12 17:06:48 - INFO - Found user's name: 'Dan Keller'
2021-12-12 17:06:48 - INFO - Already delivered to Dan Keller
2021-12-12 17:06:48 - INFO - Found user's name: 'Aron Einhorn'
2021-12-12 17:06:48 - INFO - Already delivered to Aron Einhorn
2021-12-12 17:06:48 - INFO - Found user's name: 'soner haci'
2021-12-12 17:06:48 - INFO - Already delivered to soner haci
2021-12-12 17:06:49 - INFO - Found user's name: 'Yohei Iwasaki'
2021-12-12 17:06:49 - INFO - Sending to Yohei Iwasaki
2021-12-12 17:06:49 - INFO - Using the following replace strings: '<first_name>' = 'Yohei'
2021-12-12 17:06:51 - INFO - click_x
2021-12-12 17:07:12 - INFO - Found user's name: 'Bisa E. Peterson'
2021-12-12 17:07:12 - INFO - Sending to Bisa E. Peterson
2021-12-12 17:07:12 - INFO - Using the following replace strings: '<first_name>' = 'Bisa'
2021-12-12 17:07:14 - INFO - click_x
2021-12-12 17:07:34 - INFO - Attempting to go to next page
2021-12-12 17:07:38 - INFO - Done
2021-12-13 14:24:02 - INFO - logged in
2021-12-13 14:24:03 - INFO - Processing page 1
2021-12-13 14:24:08 - ERROR - failed to find buttons
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 263, in get_user_elements
    element_list_container = self.driver.find_element_by_css_selector(
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 808, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#main > div > div > div.ph0.pv2.artdeco-card.mb2 > ul"}
  (Session info: chrome=96.0.4664.93)
Stacktrace:
Backtrace:
	Ordinal0 [0x00746903+2517251]
	Ordinal0 [0x006DF8E1+2095329]
	Ordinal0 [0x005E2848+1058888]
	Ordinal0 [0x0060D448+1233992]
	Ordinal0 [0x0060D63B+1234491]
	Ordinal0 [0x00637812+1406994]
	Ordinal0 [0x0062650A+1336586]
	Ordinal0 [0x00635BBF+1399743]
	Ordinal0 [0x0062639B+1336219]
	Ordinal0 [0x006027A7+1189799]
	Ordinal0 [0x00603609+1193481]
	GetHandleVerifier [0x008D5904+1577972]
	GetHandleVerifier [0x00980B97+2279047]
	GetHandleVerifier [0x007D6D09+534521]
	GetHandleVerifier [0x007D5DB9+530601]
	Ordinal0 [0x006E4FF9+2117625]
	Ordinal0 [0x006E98A8+2136232]
	Ordinal0 [0x006E99E2+2136546]
	Ordinal0 [0x006F3541+2176321]
	BaseThreadInitThunk [0x75AFFA29+25]
	RtlGetAppContainerNamedObjectPath [0x778C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778C7A6E+238]

2021-12-13 14:24:08 - ERROR - failed
Traceback (most recent call last):
  File "c:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 351, in <module>
    logger.info(f"Found {len(user_elements)} users on this page")
TypeError: object of type 'NoneType' has no len()
2021-12-13 14:24:12 - INFO - Done
2021-12-13 14:26:46 - INFO - logged in
2021-12-13 14:26:48 - INFO - Processing page 1
2021-12-13 14:26:48 - INFO - Found 10 users on this page
2021-12-13 14:26:48 - INFO - Found user's name: 'Clive George Cook'
2021-12-13 14:26:48 - INFO - Already delivered to Clive George Cook
2021-12-13 14:26:48 - INFO - Found user's name: 'Daniel Edwards'
2021-12-13 14:26:48 - INFO - Already delivered to Daniel Edwards
2021-12-13 14:26:48 - INFO - Found user's name: 'Eric Gallagher'
2021-12-13 14:26:48 - INFO - Already delivered to Eric Gallagher
2021-12-13 14:26:48 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-13 14:26:48 - INFO - Already delivered to Neeraj Kashyap
2021-12-13 14:26:48 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-13 14:26:48 - INFO - Already delivered to Philip D'Amelia
2021-12-13 14:26:48 - INFO - Found user's name: 'Dan Keller'
2021-12-13 14:26:48 - INFO - Already delivered to Dan Keller
2021-12-13 14:26:48 - INFO - Found user's name: 'Aron Einhorn'
2021-12-13 14:26:48 - INFO - Already delivered to Aron Einhorn
2021-12-13 14:26:48 - INFO - Found user's name: 'soner haci'
2021-12-13 14:26:48 - INFO - Already delivered to soner haci
2021-12-13 14:26:49 - INFO - Found user's name: 'Yohei Iwasaki'
2021-12-13 14:26:49 - INFO - Already delivered to Yohei Iwasaki
2021-12-13 14:26:49 - INFO - Found user's name: 'Bisa E. Peterson'
2021-12-13 14:26:49 - INFO - Already delivered to Bisa E. Peterson
2021-12-13 14:26:49 - INFO - Attempting to go to next page
2021-12-13 14:26:52 - INFO - Done
2021-12-13 14:29:24 - INFO - logged in
2021-12-13 14:29:27 - INFO - Processing page 1
2021-12-13 14:29:27 - INFO - Found 10 users on this page
2021-12-13 14:29:27 - INFO - Found user's name: 'Clive George Cook'
2021-12-13 14:29:27 - INFO - Already delivered to Clive George Cook
2021-12-13 14:29:27 - INFO - Found user's name: 'Daniel Edwards'
2021-12-13 14:29:27 - INFO - Already delivered to Daniel Edwards
2021-12-13 14:29:27 - INFO - Found user's name: 'Eric Gallagher'
2021-12-13 14:29:27 - INFO - Already delivered to Eric Gallagher
2021-12-13 14:29:27 - INFO - Found user's name: 'Neeraj Kashyap'
2021-12-13 14:29:27 - INFO - Already delivered to Neeraj Kashyap
2021-12-13 14:29:27 - INFO - Found user's name: 'Philip D'Amelia'
2021-12-13 14:29:27 - INFO - Already delivered to Philip D'Amelia
2021-12-13 14:29:27 - INFO - Found user's name: 'Dan Keller'
2021-12-13 14:29:27 - INFO - Already delivered to Dan Keller
2021-12-13 14:29:27 - INFO - Found user's name: 'Aron Einhorn'
2021-12-13 14:29:27 - INFO - Already delivered to Aron Einhorn
2021-12-13 14:29:27 - INFO - Found user's name: 'soner haci'
2021-12-13 14:29:27 - INFO - Already delivered to soner haci
2021-12-13 14:29:27 - INFO - Found user's name: 'Yohei Iwasaki'
2021-12-13 14:29:27 - INFO - Already delivered to Yohei Iwasaki
2021-12-13 14:29:27 - INFO - Found user's name: 'Bisa E. Peterson'
2021-12-13 14:29:27 - INFO - Sending to Bisa E. Peterson
2021-12-13 14:29:27 - INFO - Using the following replace strings: '<first_name>' = 'Bisa'
2021-12-13 14:29:29 - INFO - click_x
2021-12-13 14:29:46 - INFO - Attempting to go to next page
2021-12-13 14:29:49 - INFO - Done
2022-01-10 15:17:31 - INFO - https://www.linkedin.com/search/results/people/?firstName=may&lastName=moshe&network=%5B%22F%22%5D&origin=FACETED_SEARCH&sid=Z(P
2022-01-10 15:17:54 - INFO - logged in
2022-01-10 15:17:54 - INFO - Processing page 1
2022-01-10 15:17:59 - ERROR - failed to find buttons
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\from github\SocialNetworkBots\temp.py", line 224, in get_user_elements
    element_list_container = self.driver.find_element_by_css_selector(
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 802, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#main > div > div > div.ph0.pv2.artdeco-card.mb2 > ul"}
  (Session info: chrome=97.0.4692.71)
Stacktrace:
Backtrace:
	Ordinal0 [0x011EE713+2549523]
	Ordinal0 [0x011872D1+2126545]
	Ordinal0 [0x01082C88+1059976]
	Ordinal0 [0x010AE24E+1237582]
	Ordinal0 [0x010AE44B+1238091]
	Ordinal0 [0x010D9002+1413122]
	Ordinal0 [0x010C7914+1341716]
	Ordinal0 [0x010D73AA+1405866]
	Ordinal0 [0x010C7736+1341238]
	Ordinal0 [0x010A34E6+1193190]
	Ordinal0 [0x010A4376+1196918]
	GetHandleVerifier [0x01389742+1627410]
	GetHandleVerifier [0x0143A93C+2352908]
	GetHandleVerifier [0x01282AE1+551089]
	GetHandleVerifier [0x01281B03+547027]
	Ordinal0 [0x0118CBEE+2149358]
	Ordinal0 [0x01190F18+2166552]
	Ordinal0 [0x01191060+2166880]
	Ordinal0 [0x0119AC60+2206816]
	BaseThreadInitThunk [0x757FFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77227A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77227A6E+238]

2022-01-10 15:17:59 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\from github\SocialNetworkBots\temp.py", line 308, in <module>
    logger.info(f"Found {len(user_elements)} users on this page")
TypeError: object of type 'NoneType' has no len()
2022-01-10 15:18:00 - INFO - Done
2022-01-10 15:22:43 - INFO - https://www.linkedin.com/search/results/people/?firstName=may&lastName=moshe&network=%5B%22F%22%5D&origin=FACETED_SEARCH&sid=Z(P
2022-01-10 15:23:13 - INFO - logged in
2022-01-10 15:23:13 - INFO - Processing page 1
2022-01-10 15:23:13 - INFO - Found 1 users on this page
2022-01-10 15:23:13 - INFO - Found user's name: 'May Moshe'
2022-01-10 15:23:13 - INFO - Sending to May Moshe
2022-01-10 15:23:13 - INFO - Using the following replace strings: '<first_name>' = 'May'
2022-01-10 15:23:14 - INFO - send message
2022-01-10 15:23:15 - INFO - click_x
2022-01-10 15:23:31 - INFO - Attempting to go to next page
2022-01-10 15:23:34 - INFO - Done
2022-01-10 15:25:49 - INFO - https://www.linkedin.com/search/results/people/?firstName=may&lastName=moshe&network=%5B%22F%22%5D&origin=FACETED_SEARCH&sid=Z(P
2022-01-10 15:25:58 - INFO - logged in
2022-01-10 15:25:58 - INFO - Processing page 1
2022-01-10 15:26:03 - ERROR - failed to find buttons
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\from github\SocialNetworkBots\temp.py", line 224, in get_user_elements
    element_list_container = self.driver.find_element_by_css_selector(
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 802, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#main > div > div > div.ph0.pv2.artdeco-card.mb2 > ul"}
  (Session info: chrome=97.0.4692.71)
Stacktrace:
Backtrace:
	Ordinal0 [0x011EE713+2549523]
	Ordinal0 [0x011872D1+2126545]
	Ordinal0 [0x01082C88+1059976]
	Ordinal0 [0x010AE24E+1237582]
	Ordinal0 [0x010AE44B+1238091]
	Ordinal0 [0x010D9002+1413122]
	Ordinal0 [0x010C7914+1341716]
	Ordinal0 [0x010D73AA+1405866]
	Ordinal0 [0x010C7736+1341238]
	Ordinal0 [0x010A34E6+1193190]
	Ordinal0 [0x010A4376+1196918]
	GetHandleVerifier [0x01389742+1627410]
	GetHandleVerifier [0x0143A93C+2352908]
	GetHandleVerifier [0x01282AE1+551089]
	GetHandleVerifier [0x01281B03+547027]
	Ordinal0 [0x0118CBEE+2149358]
	Ordinal0 [0x01190F18+2166552]
	Ordinal0 [0x01191060+2166880]
	Ordinal0 [0x0119AC60+2206816]
	BaseThreadInitThunk [0x757FFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77227A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77227A6E+238]

2022-01-10 15:26:03 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\from github\SocialNetworkBots\temp.py", line 308, in <module>
    logger.info(f"Found {len(user_elements)} users on this page")
TypeError: object of type 'NoneType' has no len()
2022-01-10 15:26:03 - INFO - Done
2022-01-10 15:26:35 - INFO - 
2022-01-10 15:26:54 - INFO - logged in
2022-01-10 15:26:54 - INFO - Processing page 1
2022-01-10 15:27:00 - ERROR - failed to find buttons
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\from github\SocialNetworkBots\temp.py", line 224, in get_user_elements
    element_list_container = self.driver.find_element_by_css_selector(
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 802, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#main > div > div > div.ph0.pv2.artdeco-card.mb2 > ul"}
  (Session info: chrome=97.0.4692.71)
Stacktrace:
Backtrace:
	Ordinal0 [0x011EE713+2549523]
	Ordinal0 [0x011872D1+2126545]
	Ordinal0 [0x01082C88+1059976]
	Ordinal0 [0x010AE24E+1237582]
	Ordinal0 [0x010AE44B+1238091]
	Ordinal0 [0x010D9002+1413122]
	Ordinal0 [0x010C7914+1341716]
	Ordinal0 [0x010D73AA+1405866]
	Ordinal0 [0x010C7736+1341238]
	Ordinal0 [0x010A34E6+1193190]
	Ordinal0 [0x010A4376+1196918]
	GetHandleVerifier [0x01389742+1627410]
	GetHandleVerifier [0x0143A93C+2352908]
	GetHandleVerifier [0x01282AE1+551089]
	GetHandleVerifier [0x01281B03+547027]
	Ordinal0 [0x0118CBEE+2149358]
	Ordinal0 [0x01190F18+2166552]
	Ordinal0 [0x01191060+2166880]
	Ordinal0 [0x0119AC60+2206816]
	BaseThreadInitThunk [0x757FFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77227A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77227A6E+238]

2022-01-10 15:27:00 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\from github\SocialNetworkBots\temp.py", line 308, in <module>
    logger.info(f"Found {len(user_elements)} users on this page")
TypeError: object of type 'NoneType' has no len()
2022-01-10 15:27:00 - INFO - Done
2022-01-10 15:31:46 - INFO - https://www.linkedin.com/search/results/people/?firstName=may&lastName=moshe&network=%5B%22F%22%5D&origin=FACETED_SEARCH&sid=Z(P
2022-01-10 15:32:14 - INFO - logged in
2022-01-10 15:32:14 - INFO - Processing page 1
2022-01-10 15:32:14 - INFO - Found 1 users on this page
2022-01-10 15:32:14 - INFO - Found user's name: 'May Moshe'
2022-01-10 15:32:14 - INFO - Sending to May Moshe
2022-01-10 15:32:14 - INFO - Using the following replace strings: '<first_name>' = 'May'
2022-01-10 15:32:15 - INFO - send message
2022-01-10 15:32:15 - INFO - click_x
2022-01-10 15:32:31 - INFO - Attempting to go to next page
2022-01-10 15:32:37 - INFO - Done
2022-01-24 14:56:05 - INFO - [<selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="b894213c-55a8-4c26-a240-2cbcda216020")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="a813b1bb-baef-4f9f-8789-cecb5ffcb27a")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="3cceab58-9282-48aa-a773-91c282f6e588")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="d3841ea8-90af-4869-99c8-fbedfbb1a91d")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="c4ed4d09-143b-4a3f-997f-03a9348e0082")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="5576b12b-52a8-4b36-aeb2-b811c7bc8c91")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="c1564ea5-809c-4b31-925f-6b4e7f39d308")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="c6bdc88f-8283-49d5-840d-95da431ddacf")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="cdc51c73-eab1-4b5a-a629-09cd95ce5d39")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="a6560eac-88ba-4992-a89e-83b134396eee")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="56ccf0ad-e9e6-4353-8449-d1ca7fb7cbe7")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="41597342-0d22-419d-8a34-14e3ebd4e7a8")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="cfcba2fb-25fa-4284-9ca3-1f13eb471fe9")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="94622bbd-dda1-4b5f-b8a2-9ac47866c774")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="2f58e779-ceab-4c60-8ce6-4b1e21821bf1")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="183acfeb-3613-4068-8c22-ce714374c32b")>, <selenium.webdriver.remote.webelement.WebElement (session="c06d81630818319b1e9c75c614fe78fc", element="833b0d65-401b-4d64-9d48-047ce197db37")>]
2022-01-24 14:56:05 - INFO - Done
2022-01-24 14:58:35 - INFO - logged in
2022-01-24 14:58:42 - INFO - Found 17 users on this page
2022-01-24 14:58:42 - INFO - Done
2022-02-07 09:53:08 - INFO - 13
2022-02-07 09:53:08 - INFO - start prompt5 
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:10 - INFO - No success
2022-02-07 09:53:31 - INFO - logged in
2022-02-07 09:53:31 - INFO - Processing page 1
2022-02-07 09:53:31 - INFO - Found 1 users on this page
2022-02-07 09:53:31 - INFO - Found user's name: 'May Moshe'
2022-02-07 09:53:31 - INFO - Sending to May Moshe
2022-02-07 09:53:32 - INFO - Using the following replace strings: '<first_name>' = 'May'
2022-02-07 09:53:33 - INFO - send message
2022-02-07 09:53:33 - INFO - click_x
2022-02-07 09:53:35 - INFO - Attempting to go to next page
2022-02-07 09:53:35 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 397, in <module>
    apply_filter(driver, user_filter=user_filter)
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\temp.py", line 82, in apply_filter
    driver.get(user_filter)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=97.0.4692.99)
Stacktrace:
Backtrace:
	Ordinal0 [0x00546903+2517251]
	Ordinal0 [0x004DF8E1+2095329]
	Ordinal0 [0x003E2848+1058888]
	Ordinal0 [0x003CBF90+966544]
	Ordinal0 [0x00428999+1345945]
	Ordinal0 [0x00435342+1397570]
	Ordinal0 [0x0042639B+1336219]
	Ordinal0 [0x004027A7+1189799]
	Ordinal0 [0x00403609+1193481]
	GetHandleVerifier [0x006D5904+1577972]
	GetHandleVerifier [0x00780B97+2279047]
	GetHandleVerifier [0x005D6D09+534521]
	GetHandleVerifier [0x005D5DB9+530601]
	Ordinal0 [0x004E4FF9+2117625]
	Ordinal0 [0x004E98A8+2136232]
	Ordinal0 [0x004E99E2+2136546]
	Ordinal0 [0x004F3541+2176321]
	BaseThreadInitThunk [0x7695FA29+25]
	RtlGetAppContainerNamedObjectPath [0x770A7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x770A7A6E+238]

2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:03:13 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:17 - INFO - No success
2022-02-07 10:05:59 - INFO - 1
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 2
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 3
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 4
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 5
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 6
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 7
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 8
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 9
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 10
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 11
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 12
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 13
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:05:59 - INFO - 14
2022-02-07 10:05:59 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:06:58 - INFO - nir123456
2022-02-07 10:06:58 - INFO - nirmaman631@gmail.com
2022-02-07 10:06:58 - INFO - No success
2022-02-07 10:07:16 - INFO - logged in
2022-02-07 10:07:25 - INFO - Found 32 users on this page
2022-02-07 10:07:27 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\addConnections.py", line 216, in main
    AddConnectionsTracker.add_user_to_addConnections_list(fullName)
TypeError: add_user_to_addConnections_list() missing 1 required positional argument: 'full_name'
2022-02-07 10:07:28 - INFO - Done
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - nir123456
2022-02-07 10:12:46 - INFO - nirmaman631@gmail.com
2022-02-07 10:12:46 - INFO - No success
2022-02-07 10:12:46 - INFO - 1
2022-02-07 10:12:46 - INFO - 1
2022-02-07 10:13:04 - INFO - logged in
2022-02-07 10:13:12 - INFO - Found 32 users on this page
2022-02-07 10:13:14 - INFO - //ul/li[z]//*/h4
2022-02-07 10:13:14 - INFO - //ul/li[1]//*/h4
2022-02-07 10:13:14 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\addConnections.py", line 221, in main
    AddConnectionsTracker.add_user_to_addConnections_list(fullName)
TypeError: add_user_to_addConnections_list() missing 1 required positional argument: 'full_name'
2022-02-07 10:13:19 - INFO - Done
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:38 - INFO - nir123456
2022-02-07 10:16:38 - INFO - nirmaman631@gmail.com
2022-02-07 10:16:38 - INFO - No success
2022-02-07 10:16:55 - INFO - logged in
2022-02-07 10:17:03 - INFO - Found 32 users on this page
2022-02-07 10:17:05 - INFO - //ul/li[z]//*/h4
2022-02-07 10:17:05 - INFO - //ul/li[1]//*/h4
2022-02-07 10:17:05 - INFO - <selenium.webdriver.remote.webelement.WebElement (session="bd95c78e1c3f326dcb014ac93d52d052", element="caccd91b-c016-48cd-aff3-723a91a3bfd7")>
2022-02-07 10:17:05 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\addConnections.py", line 211, in main
    AddConnectionsTracker.add_user_to_addConnections_list(fullName)
TypeError: add_user_to_addConnections_list() missing 1 required positional argument: 'full_name'
2022-02-07 10:17:06 - INFO - Done
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:27 - INFO - nir123456
2022-02-07 10:20:27 - INFO - nirmaman631@gmail.com
2022-02-07 10:20:27 - INFO - No success
2022-02-07 10:20:43 - INFO - logged in
2022-02-07 10:20:51 - INFO - Found 32 users on this page
2022-02-07 10:20:53 - INFO - //ul/li[z]//*/h4
2022-02-07 10:20:53 - INFO - //ul/li[1]//*/h4
2022-02-07 10:20:53 - INFO - Shay Hershcovich
2022-02-07 10:20:53 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\addConnections.py", line 212, in main
    AddConnectionsTracker.add_user_to_addConnections_list(fullName)
TypeError: add_user_to_addConnections_list() missing 1 required positional argument: 'full_name'
2022-02-07 10:20:53 - INFO - Done
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:12 - INFO - nir123456
2022-02-07 10:24:12 - INFO - nirmaman631@gmail.com
2022-02-07 10:24:12 - INFO - No success
2022-02-07 10:24:27 - INFO - logged in
2022-02-07 10:24:35 - INFO - Found 32 users on this page
2022-02-07 10:24:37 - INFO - //ul/li[z]//*/h4
2022-02-07 10:24:37 - INFO - //ul/li[1]//*/h4
2022-02-07 10:24:37 - INFO - Shay Hershcovich
2022-02-07 10:24:37 - INFO - Done
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:30:59 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:33:40 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:36 - INFO - No success
2022-02-07 10:34:56 - INFO - logged in
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:24 - INFO - No success
2022-02-07 10:38:43 - INFO - logged in
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:39:59 - INFO - No success
2022-02-07 10:40:18 - INFO - logged in
2022-02-07 10:40:27 - INFO - im here
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:41:59 - INFO - No success
2022-02-07 10:42:18 - INFO - logged in
2022-02-07 10:42:27 - INFO - im here
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:42:57 - INFO - No success
2022-02-07 10:43:16 - INFO - logged in
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:36 - INFO - No success
2022-02-07 10:44:55 - INFO - logged in
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:35 - INFO - No success
2022-02-07 10:45:51 - INFO - logged in
2022-02-07 10:45:59 - INFO - im here
2022-02-07 10:45:59 - INFO - Found 6 users on this page
2022-02-07 10:45:59 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\withdrawConnections.py", line 195, in main
    for x in range(1, numberOfPeople):
TypeError: 'list' object cannot be interpreted as an integer
2022-02-07 10:46:04 - INFO - Done
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:32 - INFO - No success
2022-02-07 10:47:47 - INFO - logged in
2022-02-07 10:48:05 - INFO - im here
2022-02-07 10:48:05 - INFO - Found 6 users on this page
2022-02-07 10:48:05 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\withdrawConnections.py", line 195, in main
    for x in range(1, numberOfPeople):
TypeError: 'list' object cannot be interpreted as an integer
2022-02-07 10:48:06 - INFO - Done
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:40 - INFO - No success
2022-02-07 10:48:41 - INFO - No success
2022-02-07 10:48:41 - INFO - No success
2022-02-07 10:48:57 - INFO - logged in
2022-02-07 10:49:06 - INFO - im here
2022-02-07 10:49:06 - INFO - Found 6 users on this page
2022-02-07 10:49:06 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\withdrawConnections.py", line 195, in main
    for x in range(1, numberOfPeople):
TypeError: 'list' object cannot be interpreted as an integer
2022-02-07 10:49:07 - INFO - Done
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 10:50:39 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:12 - INFO - No success
2022-02-07 11:04:30 - INFO - logged in
2022-02-07 11:04:37 - INFO - im here
2022-02-07 11:04:37 - INFO - Found 6 users on this page
2022-02-07 11:04:37 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\withdrawConnections.py", line 196, in main
    for x in range(1, numberOfPeople):
TypeError: 'list' object cannot be interpreted as an integer
2022-02-07 11:04:38 - INFO - Done
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:15 - INFO - No success
2022-02-07 11:06:38 - INFO - logged in
2022-02-07 11:06:49 - INFO - im here
2022-02-07 11:06:49 - INFO - Found 6 users on this page
2022-02-07 11:06:51 - INFO - im here
2022-02-07 11:06:51 - INFO - im here2
2022-02-07 11:06:51 - INFO - Shay Hershcovich
2022-02-07 11:06:51 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\withdrawConnections.py", line 207, in main
    driver.find_element_by_xpath(xpath).click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 520, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: Unable to locate an element with the xpath expression //li[1]//div/button[te1t()] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//li[1]//div/button[te1t()]' is not a valid XPath expression.
  (Session info: chrome=97.0.4692.99)
Stacktrace:
Backtrace:
	Ordinal0 [0x00546903+2517251]
	Ordinal0 [0x004DF8E1+2095329]
	Ordinal0 [0x003E2848+1058888]
	Ordinal0 [0x003E4F44+1068868]
	Ordinal0 [0x003E4E0E+1068558]
	Ordinal0 [0x003E5070+1069168]
	Ordinal0 [0x0040D1C2+1233346]
	Ordinal0 [0x0040D63B+1234491]
	Ordinal0 [0x00437812+1406994]
	Ordinal0 [0x0042650A+1336586]
	Ordinal0 [0x00435BBF+1399743]
	Ordinal0 [0x0042639B+1336219]
	Ordinal0 [0x004027A7+1189799]
	Ordinal0 [0x00403609+1193481]
	GetHandleVerifier [0x006D5904+1577972]
	GetHandleVerifier [0x00780B97+2279047]
	GetHandleVerifier [0x005D6D09+534521]
	GetHandleVerifier [0x005D5DB9+530601]
	Ordinal0 [0x004E4FF9+2117625]
	Ordinal0 [0x004E98A8+2136232]
	Ordinal0 [0x004E99E2+2136546]
	Ordinal0 [0x004F3541+2176321]
	BaseThreadInitThunk [0x7695FA29+25]
	RtlGetAppContainerNamedObjectPath [0x770A7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x770A7A6E+238]

2022-02-07 11:06:53 - INFO - Done
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:09:47 - INFO - No success
2022-02-07 11:10:00 - INFO - logged in
2022-02-07 11:10:07 - INFO - im here
2022-02-07 11:10:07 - INFO - Found 6 users on this page
2022-02-07 11:10:09 - INFO - im here
2022-02-07 11:10:09 - INFO - im here2
2022-02-07 11:10:09 - INFO - Shay Hershcovich
2022-02-07 11:10:11 - INFO - im here
2022-02-07 11:10:11 - INFO - im here2
2022-02-07 11:10:11 - INFO - zohar maman
2022-02-07 11:10:12 - ERROR - failed
Traceback (most recent call last):
  File "C:\Users\maymo\OneDrive - Azrieli - Jerusalem College of Engineering\פרוייקט גמר\SocialNetworkBots\SocialNetworkBots\withdrawConnections.py", line 207, in main
    driver.find_element_by_xpath(xpath).click()
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maymo\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Withdraw invitation sent to zohar maman" id="ember48" class="artdeco-button artdeco-button--muted artdeco-button--3 artdeco-button--tertiary ember-view invitation-card__action-btn">...</button> is not clickable at point (798, 362). Other element would receive the click: <div id="ember161" class="artdeco-modal__content ember-view">...</div>
  (Session info: chrome=97.0.4692.99)
Stacktrace:
Backtrace:
	Ordinal0 [0x00546903+2517251]
	Ordinal0 [0x004DF8E1+2095329]
	Ordinal0 [0x003E2848+1058888]
	Ordinal0 [0x00413509+1258761]
	Ordinal0 [0x00411868+1251432]
	Ordinal0 [0x0040F65D+1242717]
	Ordinal0 [0x0040E4A8+1238184]
	Ordinal0 [0x00404037+1196087]
	Ordinal0 [0x004264D3+1336531]
	Ordinal0 [0x00403A36+1194550]
	Ordinal0 [0x004265BA+1336762]
	Ordinal0 [0x00435BBF+1399743]
	Ordinal0 [0x0042639B+1336219]
	Ordinal0 [0x004027A7+1189799]
	Ordinal0 [0x00403609+1193481]
	GetHandleVerifier [0x006D5904+1577972]
	GetHandleVerifier [0x00780B97+2279047]
	GetHandleVerifier [0x005D6D09+534521]
	GetHandleVerifier [0x005D5DB9+530601]
	Ordinal0 [0x004E4FF9+2117625]
	Ordinal0 [0x004E98A8+2136232]
	Ordinal0 [0x004E99E2+2136546]
	Ordinal0 [0x004F3541+2176321]
	BaseThreadInitThunk [0x7695FA29+25]
	RtlGetAppContainerNamedObjectPath [0x770A7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x770A7A6E+238]

2022-02-07 11:10:13 - INFO - Done
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - No success
2022-02-07 12:17:28 - INFO - nir123456
2022-02-07 12:17:28 - INFO - nirmaman631@gmail.com
2022-02-07 12:17:28 - INFO - No success
